routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Notifications\VerifyUser;
use App\Models\User;
// use App\Http\Controllers\StoreController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->away(env('HOME_URL'));
    // return view('welcome');
});

Route::get('/privacy', function () {
    return view('privacy');
});

Route::get('/verified', function () {
    return view('verified');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('stores', StoreController::class);
    Route::resource('payment-methods', PaymentMethodController::class);
    Route::resource('exchange-rates', ExchangeRateController::class);
    Route::resource('orders', OrderController::class);
    Route::resource('categories', CategoryController::class);
    Route::resource('slides', SlideController::class);
    Route::resource('institutes', InstituteController::class);

//-----------------------------------------------------------------------------------------
//  STORE
//-----------------------------------------------------------------------------------------    
    Route::get('/stores/suspend/{id}', [App\Http\Controllers\StoreController::class, 'suspend'])->name('stores.suspend');
    Route::get('/stores/activate/{id}', [App\Http\Controllers\StoreController::class, 'activate'])->name('stores.activate');
    Route::get('/stores/hide/{id}', [App\Http\Controllers\StoreController::class, 'hide'])->name('stores.hide');
    Route::get('/stores/show/{id}', [App\Http\Controllers\StoreController::class, 'show'])->name('stores.show');

//-----------------------------------------------------------------------------------------
//  PAYMENT METHODS
//-----------------------------------------------------------------------------------------    
// Route::get('/payment-methods/edit/{id}', [App\Http\Controllers\PaymentMethodController::class, 'suspend'])->name('payment-methods.edit');
Route::get('/payment-methods/suspend/{id}', [App\Http\Controllers\PaymentMethodController::class, 'suspend'])->name('payment-methods.suspend');
Route::get('/payment-methods/activate/{id}', [App\Http\Controllers\PaymentMethodController::class, 'activate'])->name('payment-methods.activate');


//-----------------------------------------------------------------------------------------
//  ORDERS
//-----------------------------------------------------------------------------------------    
Route::get('/order/approve/{id}', [App\Http\Controllers\OrderController::class, 'approve'])->name('order.approve');
Route::get('/order/cancel/{id}', [App\Http\Controllers\OrderController::class, 'cancel'])->name('order.cancel');
Route::get('/order/deliver/{id}', [App\Http\Controllers\OrderController::class, 'deliver'])->name('order.deliver');
Route::get('/order/delivered/{id}', [App\Http\Controllers\OrderController::class, 'delivered'])->name('order.delivered');

//-----------------------------------------------------------------------------------------
//  EXCHANGE RATE
//-----------------------------------------------------------------------------------------    
// Route::get('/payment-methods/edit/{id}', [App\Http\Controllers\PaymentMethodController::class, 'suspend'])->name('payment-methods.edit');
// Route::get('/exchange/suspend/{id}', [App\Http\Controllers\PaymentMethodController::class, 'suspend'])->name('payment-methods.suspend');
// Route::get('/payment-methods/activate/{id}', [App\Http\Controllers\PaymentMethodController::class, 'activate'])->name('payment-methods.activate');
Route::get('/exchanges/fixate/{id}', [App\Http\Controllers\ExchangeRateController::class, 'fixate'])->name('exchange-rates.fixate');
Route::get('/exchanges/release/{id}', [App\Http\Controllers\ExchangeRateController::class, 'release'])->name('exchange-rates.release');
Route::get('/exchanges/refresh', [App\Http\Controllers\ExchangeRateController::class, 'refresh'])->name('exchange-rates.refresh');

//-----------------------------------------------------------------------------------------
//  SLIDES
//-----------------------------------------------------------------------------------------    
Route::get('/slides/suspend/{id}', [App\Http\Controllers\SlideController::class, 'suspend'])->name('slides.suspend');
Route::get('/slides/activate/{id}', [App\Http\Controllers\SlideController::class, 'activate'])->name('slides.activate');

//-----------------------------------------------------------------------------------------
//  INSTITUTES
//-----------------------------------------------------------------------------------------    
Route::get('/institutes/suspend/{id}', [App\Http\Controllers\InstituteController::class, 'suspend'])->name('institutes.suspend');
Route::get('/institutes/activate/{id}', [App\Http\Controllers\InstituteController::class, 'activate'])->name('institutes.activate');

});






Route::get('/notification/verify-user', function () {
    $user = User::all()->first();

    // Mail::to('consultoria@iideas.biz')->send(new VerifyUser($user));
    $user->notify(new VerifyUser($user));

    return (new VerifyUser($user))
                ->toMail($user);
});

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;


use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\Controller;
use App\Models\Institute;
use App\Models\User;
use App\Models\Store;
use Illuminate\Support\Facades\Hash;
use ImageOptimizer;
use Intervention\Image\ImageManagerStatic as Image;
use DB;
use Exception;
use Carbon\Carbon;

class UserController extends Controller
{

    public function update(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'last_name' => 'required',
            'email' => 'required|email|unique:users,email,' . auth()->user()->id,
        ]);

        $user = User::find(auth()->user()->id);

        if (is_null($user)) {
            $response = [
                'error' => 'Not authorized',
                'message' => 'This action has been logged and you may be suspended'
            ];
            return response()->json($response, 401);
        }

        $user->fill($request->except(['password', 'graduate', 'postgraduate', 'certified', 'courses', 'offices']));

        if ($request->get('password')) {
            $user->password = Hash::make($request->get('password'));
        }

        $user->save();

        // Validate if the profile image is received
        $profile_images = $request->input('image_data.*');


        if (is_array($profile_images) && count($profile_images) > 0) {

            $folderPath = "images/" . $user->id . "/";
            $image_parts = explode(";base64,", $profile_images[0]);
            $image_type_aux = explode("image/", $image_parts[0]);
            $image_type = $image_type_aux[1];
            $image_base64 = base64_decode($image_parts[1]);
            $file = $folderPath . uniqid() . '.' . $image_type;

            if (Storage::disk('public_uploads')->put($file, $image_base64)) {

                // Resize if image is too wide
                $img = Image::make(public_path() . '/uploads/' . $file);

                if ($img->width() > 1200) {
                    $img->resize(1200, null, function ($constraint) {
                        $constraint->aspectRatio();
                    });

                    $img->save(public_path() . '/uploads/' . $file);
                }

                // Optimize image
                ImageOptimizer::optimize(public_path() . '/uploads/' . $file);

                $user->profile_image = $file;
                $user->save();
            } else {
                $response = [
                    'error' => 'File upload failed',
                    'message' => 'We could not upload your file'
                ];
                return response()->json($response, 401);
            }
        }

        //Update store's player_id based on email
        $store = Store::where('store_email', $user->email)->get()->first();

        if (!is_null($store)) {
            $store->player_id = $user->player_id;
            $store->save();
        }

        //Updating educational information

        //Graduate studies
        $graduate = json_decode($request->get('graduate'));

        $pregraduate = DB::table('users_institutes')
            ->where('degree_name', 'Graduate')
            ->where('user_id', auth()->user()->id)->get()->first();

        if (property_exists($graduate, 'degree_local_number')){
            if (is_null($pregraduate)) {
                DB::table('users_institutes')->insert(['created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'degree_local_number' => $graduate->degree_local_number, 'degree_national_number' => $graduate->degree_national_number, 'user_id' => auth()->user()->id, 'institute_id' => $graduate->institute_id, 'degree_name' => $graduate->degree_name]);
            } else {
                DB::table('users_institutes')
                    ->where('degree_name', 'Graduate')
                    ->where('user_id', auth()->user()->id)
                    ->update(['updated_at' => Carbon::now(), 'degree_local_number' => $graduate->degree_local_number, 'degree_national_number' => $graduate->degree_national_number, 'institute_id' => $graduate->institute_id]);
            }
        }

        //Postraduate studies
        $postgraduates = json_decode($request->get('postgraduate'));

        foreach ($postgraduates as $postgraduate) {

            //Detect Institute

            $institute = Institute::whereRaw("lower(trim(institute_name)) = '" . strtolower(trim($postgraduate->degree_custom_institute)) . "'")->get()->first();

            if (is_null($institute)) {
                $institute = new Institute();

                $institute->institute_type = 'Universidad';
                $institute->institute_name = $postgraduate->degree_custom_institute;
                $institute->is_active = true;
                $institute->created_at = Carbon::now();
                $institute->updated_at = Carbon::now();

                $institute->save();
            }

            $postgraduate->institute_id = $institute->id;


            if (isset($postgraduate->id)) {
                DB::table('users_institutes')
                    ->where('id', $postgraduate->id)
                    ->update([
                        'updated_at' => Carbon::now(),
                        'degree_name' => 'Postgraduate',
                        'degree_title' => $postgraduate->degree_title,
                        'user_id' => auth()->user()->id,
                        'degree_custom_institute' => $postgraduate->degree_custom_institute,
                        'institute_id' => $postgraduate->institute_id
                    ]);
            } else {
                DB::table('users_institutes')
                    ->insert([
                        'updated_at' => Carbon::now(),
                        'degree_name' => 'Postgraduate',
                        'degree_title' => $postgraduate->degree_title,
                        'user_id' => auth()->user()->id,
                        'degree_custom_institute' => $postgraduate->degree_custom_institute,
                        'institute_id' => $postgraduate->institute_id
                    ]);
            }
        }

        //Certified studies
        $certified = json_decode($request->get('certified'));

        foreach ($certified as $certificate) {

            //Detect Institute

            $institute = Institute::whereRaw("lower(trim(institute_name)) = '" . strtolower(trim($certificate->degree_custom_institute)) . "'")->get()->first();

            if (is_null($institute)) {
                $institute = new Institute();

                $institute->institute_type = 'Instituto';
                $institute->institute_name = $certificate->degree_custom_institute;
                $institute->is_active = true;
                $institute->created_at = Carbon::now();
                $institute->updated_at = Carbon::now();

                $institute->save();
            }

            $certificate->institute_id = $institute->id;

            if (isset($certificate->id)) {
                DB::table('users_institutes')
                    ->where('id', $certificate->id)
                    ->update([
                        'updated_at' => Carbon::now(),
                        'degree_name' => 'Certificate',
                        'degree_title' => $certificate->degree_title,
                        'user_id' => auth()->user()->id,
                        'degree_custom_institute' => $certificate->degree_custom_institute,
                        'institute_id' => $certificate->institute_id
                    ]);
            } else {
                DB::table('users_institutes')
                    ->insert([
                        'updated_at' => Carbon::now(),
                        'degree_name' => 'Certificate',
                        'degree_title' => $certificate->degree_title,
                        'user_id' => auth()->user()->id,
                        'degree_custom_institute' => $certificate->degree_custom_institute,
                        'institute_id' => $certificate->institute_id
                    ]);
            }
        }

        //Courses studies
        $courses = json_decode($request->get('courses'));

        foreach ($courses as $course) {

            //Detect Institute

            $institute = Institute::whereRaw("lower(trim(institute_name)) = '" . strtolower(trim($course->degree_custom_institute)) . "'")->get()->first();

            if (is_null($institute)) {
                $institute = new Institute();

                $institute->institute_type = 'Instituto';
                $institute->institute_name = $course->degree_custom_institute;
                $institute->is_active = true;
                $institute->created_at = Carbon::now();
                $institute->updated_at = Carbon::now();

                $institute->save();
            }

            $course->institute_id = $institute->id;

            if (isset($course->id)) {
                DB::table('users_institutes')
                    ->where('id', $course->id)
                    ->update([
                        'updated_at' => Carbon::now(),
                        'degree_name' => 'Course',
                        'degree_title' => $course->degree_title,
                        'user_id' => auth()->user()->id,
                        'degree_custom_institute' => $course->degree_custom_institute,
                        'institute_id' => $course->institute_id
                    ]);
            } else {
                DB::table('users_institutes')
                    ->insert([
                        'updated_at' => Carbon::now(),
                        'degree_name' => 'Course',
                        'degree_title' => $course->degree_title,
                        'user_id' => auth()->user()->id,
                        'degree_custom_institute' => $course->degree_custom_institute,
                        'institute_id' => $course->institute_id

resources/views/users/create.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Crear Nuevo Usuario</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('users.index') }}"> Regresar</a>
        </div>
    </div>
</div>


@if (count($errors) > 0)
  <div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
       @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
       @endforeach
    </ul>
  </div>
@endif



{!! Form::open(array('route' => 'users.store','method'=>'POST')) !!}
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Email:</strong>
            {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Password:</strong>
            {!! Form::password('password', array('placeholder' => 'Password','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Confirm Password:</strong>
            {!! Form::password('confirm-password', array('placeholder' => 'Confirm Password','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Role:</strong>
            {!! Form::select('roles[]', $roles,[], array('class' => 'form-control','multiple')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>
{!! Form::close() !!}

@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Editar Usuario</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('users.index') }}"> Volver</a>
        </div>
    </div>
</div>


@if (count($errors) > 0)
  <div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
       @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
       @endforeach
    </ul>
  </div>
@endif


{!! Form::model($user, ['method' => 'PATCH','route' => ['users.update', $user->id]]) !!}
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Nombre:</strong>
            {!! Form::text('name', null, array('placeholder' => 'Nombre','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Apellido:</strong>
            {!! Form::text('last_name', null, array('placeholder' => 'Apellido','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Estado:</strong>
            {!! Form::text('location', null, array('placeholder' => 'Estado','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Email:</strong>
            {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Password:</strong>
            {!! Form::password('password', array('placeholder' => 'Password','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Confirm Password:</strong>
            {!! Form::password('confirm-password', array('placeholder' => 'Confirm Password','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Role:</strong>
            {!! Form::select('roles[]', $roles,$userRole, array('class' => 'form-control','multiple')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Guardar</button>
    </div>
</div>
{!! Form::close() !!}

@endsection

resources/views/users/index.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h2>Administración de Usuarios</h2>
    </div>
    <div class="pull-right">
      <a class="btn btn-success" href="{{ route('users.create') }}"> Crear Nuevo Usuario</a>
    </div>
  </div>
</div>


@if ($message = Session::get('success'))
<div class="alert alert-success">
  <p>{{ $message }}</p>
</div>
@endif


<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable">

        <thead>
          <tr>
            <th>ID</th>
            <th>Nombre y Apellido</th>
            <th>Email / Teléfono</th>
            <th>Rol</th>
            <th width="280px">Acción</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($data as $user)
          <tr>
            <td>{{ $user->id }}</td>
            <td>{{ $user->name . ' ' . $user->last_name }}</td>
            <td>{{ $user->email }} / {{ $user->phone }}</td>
            <td>
              @if(!empty($user->getRoleNames()))
              @foreach($user->getRoleNames() as $v)
              <label class="badge badge-success">{{ $v }}</label>
              @endforeach
              @endif
            </td>
            <td>
              <a class="btn btn-info" href="{{ route('users.show',$user->id) }}">Mostrar</a>
              <a class="btn btn-primary" href="{{ route('users.edit',$user->id) }}">Editar</a>
              {!! Form::open(['method' => 'DELETE','route' => ['users.destroy', $user->id],'style'=>'display:inline']) !!}
              {!! Form::submit('Eliminar', ['class' => 'btn btn-danger']) !!}
              {!! Form::close() !!}
            </td>
          </tr>
          @endforeach
        </tbody>
        <tfoot>
          <tr>
            <th></th>
            <th><input type="text" placeholder="Buscar" /></th>
            <th><input type="text" placeholder="Buscar" /></th>
            <th><input type="text" placeholder="Buscar" /></th>
            <th style="width: 120px"></th>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>

@endsection

resources/views/users/show.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Show User</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('users.index') }}"> Back</a>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {{ $user->name }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Email:</strong>
            {{ $user->email }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Roles:</strong>
            @if(!empty($user->getRoleNames()))
                @foreach($user->getRoleNames() as $v)
                    <label class="badge badge-success">{{ $v }}</label>
                @endforeach
            @endif
        </div>
    </div>
</div>
@endsection