routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Notifications\VerifyUser;
use App\Models\User;
// use App\Http\Controllers\StoreController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->away(env('HOME_URL'));
    // return view('welcome');
});

Route::get('/privacy', function () {
    return view('privacy');
});

Route::get('/verified', function () {
    return view('verified');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('stores', StoreController::class);
    Route::resource('payment-methods', PaymentMethodController::class);
    Route::resource('exchange-rates', ExchangeRateController::class);
    Route::resource('orders', OrderController::class);
    Route::resource('categories', CategoryController::class);
    Route::resource('slides', SlideController::class);
    Route::resource('institutes', InstituteController::class);

//-----------------------------------------------------------------------------------------
//  STORE
//-----------------------------------------------------------------------------------------    
    Route::get('/stores/suspend/{id}', [App\Http\Controllers\StoreController::class, 'suspend'])->name('stores.suspend');
    Route::get('/stores/activate/{id}', [App\Http\Controllers\StoreController::class, 'activate'])->name('stores.activate');
    Route::get('/stores/hide/{id}', [App\Http\Controllers\StoreController::class, 'hide'])->name('stores.hide');
    Route::get('/stores/show/{id}', [App\Http\Controllers\StoreController::class, 'show'])->name('stores.show');

//-----------------------------------------------------------------------------------------
//  PAYMENT METHODS
//-----------------------------------------------------------------------------------------    
// Route::get('/payment-methods/edit/{id}', [App\Http\Controllers\PaymentMethodController::class, 'suspend'])->name('payment-methods.edit');
Route::get('/payment-methods/suspend/{id}', [App\Http\Controllers\PaymentMethodController::class, 'suspend'])->name('payment-methods.suspend');
Route::get('/payment-methods/activate/{id}', [App\Http\Controllers\PaymentMethodController::class, 'activate'])->name('payment-methods.activate');


//-----------------------------------------------------------------------------------------
//  ORDERS
//-----------------------------------------------------------------------------------------    
Route::get('/order/approve/{id}', [App\Http\Controllers\OrderController::class, 'approve'])->name('order.approve');
Route::get('/order/cancel/{id}', [App\Http\Controllers\OrderController::class, 'cancel'])->name('order.cancel');
Route::get('/order/deliver/{id}', [App\Http\Controllers\OrderController::class, 'deliver'])->name('order.deliver');
Route::get('/order/delivered/{id}', [App\Http\Controllers\OrderController::class, 'delivered'])->name('order.delivered');

//-----------------------------------------------------------------------------------------
//  EXCHANGE RATE
//-----------------------------------------------------------------------------------------    
// Route::get('/payment-methods/edit/{id}', [App\Http\Controllers\PaymentMethodController::class, 'suspend'])->name('payment-methods.edit');
// Route::get('/exchange/suspend/{id}', [App\Http\Controllers\PaymentMethodController::class, 'suspend'])->name('payment-methods.suspend');
// Route::get('/payment-methods/activate/{id}', [App\Http\Controllers\PaymentMethodController::class, 'activate'])->name('payment-methods.activate');
Route::get('/exchanges/fixate/{id}', [App\Http\Controllers\ExchangeRateController::class, 'fixate'])->name('exchange-rates.fixate');
Route::get('/exchanges/release/{id}', [App\Http\Controllers\ExchangeRateController::class, 'release'])->name('exchange-rates.release');
Route::get('/exchanges/refresh', [App\Http\Controllers\ExchangeRateController::class, 'refresh'])->name('exchange-rates.refresh');

//-----------------------------------------------------------------------------------------
//  SLIDES
//-----------------------------------------------------------------------------------------    
Route::get('/slides/suspend/{id}', [App\Http\Controllers\SlideController::class, 'suspend'])->name('slides.suspend');
Route::get('/slides/activate/{id}', [App\Http\Controllers\SlideController::class, 'activate'])->name('slides.activate');

//-----------------------------------------------------------------------------------------
//  INSTITUTES
//-----------------------------------------------------------------------------------------    
Route::get('/institutes/suspend/{id}', [App\Http\Controllers\InstituteController::class, 'suspend'])->name('institutes.suspend');
Route::get('/institutes/activate/{id}', [App\Http\Controllers\InstituteController::class, 'activate'])->name('institutes.activate');

});






Route::get('/notification/verify-user', function () {
    $user = User::all()->first();

    // Mail::to('consultoria@iideas.biz')->send(new VerifyUser($user));
    $user->notify(new VerifyUser($user));

    return (new VerifyUser($user))
                ->toMail($user);
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>{{ config('app.name', 'Odontoenlace') }}</title>

  <!-- Scripts -->
  <script src="{{ asset('resources/js/app.js') }}"></script>

  <!-- Fonts -->
  <link rel="dns-prefetch" href="//fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

  <!-- Styles -->
  <link href="{{ asset('resources/css/app.css') }}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{{asset('/vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet" type="text/css" />
  <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css" rel="stylesheet" />


  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>

<body>
  <div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
      <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
          {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Left Side Of Navbar -->
          <ul class="navbar-nav mr-auto">

          </ul>

          <!-- Right Side Of Navbar -->
          <ul class="navbar-nav ml-auto">
            <!-- Authentication Links -->
            @guest
            @if (Route::has('login'))
            <li class="nav-item">
              <a class="nav-link" href="{{ route('login') }}">{{ __('Iniciar Sesión') }}</a>
            </li>
            @endif

            @if (Route::has('register'))
            <li class="nav-item">
              <a class="nav-link" href="{{ route('register') }}">{{ __('Registrarse') }}</a>
            </li>
            @endif
            @else
            <li><a class="nav-link" href="{{ route('orders.index') }}">Pedidos</a></li>
            <li><a class="nav-link" href="{{ route('payment-methods.index') }}">Formas de Pago</a></li>
            <li><a class="nav-link" href="{{ route('exchange-rates.index') }}">Tasas de Cambio</a></li>
            <li><a class="nav-link" href="{{ route('users.index') }}">Usuarios</a></li>
            <li><a class="nav-link" href="{{ route('roles.index') }}">Roles</a></li>
            <li><a class="nav-link" href="{{ route('categories.index') }}">Categorías</a></li>
            <li><a class="nav-link" href="{{ route('institutes.index') }}">Instituciones</a></li>
            <li><a class="nav-link" href="{{ route('slides.index') }}">Slides</a></li>
            <li><a class="nav-link" href="{{ route('stores.index') }}">Tiendas</a></li>
            <li class="nav-item dropdown">
              <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                {{ Auth::user()->name }}
              </a>

              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                  {{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                  @csrf
                </form>
              </div>
            </li>
            @endguest
          </ul>
        </div>
      </div>
    </nav>

    <main class="py-4">
      @yield('content')
    </main>
  </div>

  <!-- Page level custom scripts -->
  <script src="{{asset('/vendor/datatables/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('/vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>


  <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>

  <script>
    $(document).ready(function() {

      $('#dataTable').DataTable({
        responsive: true,
        bSort: false,
        dom: 'Bfrtip',
        buttons: [
          'copy', 'csv', 'excel', 'pdf', 'print'
        ]
      }).columns().every(function() {
        var that = this;

        $('input', this.footer()).on('keyup change clear', function() {
          if (that.search() !== this.value) {
            that
              .search(this.value)
              .draw();
          }
        });
      });
    });
  </script>
</body>

</html>

resources/views/layouts/headless.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>{{ config('app.name', 'Odontoenlace') }}</title>

  <!-- Scripts -->
  <script src="{{ asset('resources/js/app.js') }}"></script>

  <!-- Fonts -->
  <link rel="dns-prefetch" href="//fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

  <!-- Styles -->
  <link href="{{ asset('resources/css/app.css') }}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{{asset('/vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet" type="text/css" />
  <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css" rel="stylesheet" />


  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>

<body>
  <div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
      <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
          {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Left Side Of Navbar -->
          <ul class="navbar-nav mr-auto">

          </ul>
        </div>
      </div>
    </nav>

    <main class="py-4">
      @yield('content')
    </main>
  </div>

  <!-- Page level custom scripts -->
  <script src="{{asset('/vendor/datatables/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('/vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>


  <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>

  <script>
    $(document).ready(function() {

      $('#dataTable').DataTable({
        responsive: true,
        bSort: false,
        dom: 'Bfrtip',
        buttons: [
          'copy', 'csv', 'excel', 'pdf', 'print'
        ]
      }).columns().every(function() {
        var that = this;

        $('input', this.footer()).on('keyup change clear', function() {
          if (that.search() !== this.value) {
            that
              .search(this.value)
              .draw();
          }
        });
      });
    });
  </script>
</body>

</html>